### ISSUE TITLE
Getting NPE when running mvn clean install

### ISSUE THREAD

**Issue by khajam** [intuit/maven-build-scanner#80]
java.lang.NullPointerException
	at com.intuit.maven.extensions.build.scanner.LifecycleProfiler.getBranch(LifecycleProfiler.java:225)
	at com.intuit.maven.extensions.build.scanner.LifecycleProfiler.onEvent(LifecycleProfiler.java:93)
	at com.intuit.maven.extensions.build.scanner.LifecycleProfilerTest.testSessionProfile(LifecycleProfilerTest.java:78)

**Comment by alexec** [comment]
https://github.com/intuit/maven-build-scanner/blob/81fcd8aef5fc30e5c30e489bf6f2f1ef6460ec10/src/main/java/com/intuit/maven/extensions/build/scanner/LifecycleProfiler.java#L225

Can you run `git status`?

**Comment by khajam** [comment]
This is my bad.. I took a zipped version of the repository and didn't run git init on the copied directory. I did it now and it works fine. Thanks for the quick response!
